# Generated by Django 6.0.2 on 2026-02-09 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_discussion_discussionreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='likes',
        ),
        migrations.AddField(
            model_name='discussion',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
