# Generated by Django 6.0.2 on 2026-02-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
