# Generated by Django 6.0.2 on 2026-03-06 22:45

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('objects', core.models.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='discussion',
            managers=[
                ('objects', core.models.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='discussionreply',
            managers=[
                ('objects', core.models.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.SoftDeleteManager()),
            ],
        ),
    ]
