# Generated by Django 6.0.2 on 2026-03-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_password_reset_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('BICTORYS', 'Bictorys'), ('STRIPE', 'Stripe')], default='BICTORYS', max_length=50),
        ),
    ]
